version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: champions_league
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: champions_league_db
    ports:
      - "5429:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
